name: CI

on:
  push:
    branches: [ci, master]
  schedule:
    - cron: "* 9 * * *"

jobs:
  ci:
    runs-on: windows-latest
    outputs:
      remote_ver: ${{ steps.compare.outputs.remote_ver }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: init
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          $context = $ENV:GITHUB_CONTEXT | ConvertFrom-JSON
          git config --global user.email ($context.repository_owner + '+github@gmail.com')
          git config --global user.name $context.repository_owner
          git config --global core.safecrlf false

          $info = [PSCustomObject]@{
            'Event'        = $ENV:GITHUB_EVENT_NAME
            'CommitMsg'    = (gc $ENV:GITHUB_EVENT_PATH | ConvertFrom-Json).commits.message
            'Ref'          = $ENV:GITHUB_REF
            'VersionOS'    = $PSVersionTable["OS"].toString()
            'VersionChoco' = choco --version
            'VersionGit'   = (git --version).split(' ')[-1]
          }

          $info | fl *
      - name: install
        shell: pwsh
        run: |
          git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
          . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version
      - name: "invoke test_all if running on 'ci' branch"
        shell: powershell # Instead of pwsh because au fails on pwsh core.
        if: contains(github.ref, 'ci')
        env:
          gist_id_test: "cb0f8e31c631a03beb28be380b58c056"
          github_api_key: ${{ secrets.GH_TOKEN }}
          github_user_repo: ${{ github.repository }}
          au_WhatIf: "true"
          au_Force: "true"
          au_Push: "false"
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
          $ErrorActionPreference = 'Continue'
          ./test_all.ps1
      - name: trigger au
        shell: powershell # Instead of pwsh because au fails on pwsh core.
        if: ( contains(github.event_name, 'schedule') && contains(github.ref, 'master') ) || contains(github.ref, 'master')
        env:
          au_WhatIf: "false"
          au_Force: "false"
          au_Push: "true"
        run: |
          ./update_all.ps1
      - name: upload artifact
        shell: powershell # Instead of pwsh because au fails on pwsh core.
        run: |
          7z a au_temp.zip $Env:TEMP\chocolatey\au\*
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: au_temp
          path: au_temp.zip
